// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj55d0uqhi0ZrUrbN_cAG00boM9YjHO44',
    appId: '1:368854254688:web:bf8efb2c49a56577442f05',
    messagingSenderId: '368854254688',
    projectId: 'flutter-ecom-project-3beea',
    authDomain: 'flutter-ecom-project-3beea.firebaseapp.com',
    storageBucket: 'flutter-ecom-project-3beea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5k06Rknc0sEoS-WYn5SjbiiZl4h0LLuU',
    appId: '1:368854254688:android:03c4d0e576588c90442f05',
    messagingSenderId: '368854254688',
    projectId: 'flutter-ecom-project-3beea',
    storageBucket: 'flutter-ecom-project-3beea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0L71c1PV5Z5srdNSDG8i9dAKVvOOx0E',
    appId: '1:368854254688:ios:4c2f0c47b0ad5520442f05',
    messagingSenderId: '368854254688',
    projectId: 'flutter-ecom-project-3beea',
    storageBucket: 'flutter-ecom-project-3beea.appspot.com',
    iosBundleId: 'com.example.flutterProjectEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0L71c1PV5Z5srdNSDG8i9dAKVvOOx0E',
    appId: '1:368854254688:ios:b60fd872c1be7d7b442f05',
    messagingSenderId: '368854254688',
    projectId: 'flutter-ecom-project-3beea',
    storageBucket: 'flutter-ecom-project-3beea.appspot.com',
    iosBundleId: 'com.example.flutterProjectEcom.RunnerTests',
  );
}
